.TH MONSTERS 1 "March 2025" "Angband Monsters" "Game Manual"
.SH NAME
monsters - List of monsters in Angband
.SH SYNOPSIS
.B monsters
[\fIOPTIONS\fR]
.SH DESCRIPTION
The following commands allow you to interact with the monster list from Angband:

.B --list
Displays the full list of monsters.

.B --search <monster_name>
Searches for monsters with names containing <monster_name>.

.B --edit <monster_name>
Shows monster detail window of <monster_name> and provides edit functionality.

Example usage:
.B python3 /path/to/monsters.py --list
.B python3 /path/to/monsters.py --search Goblin

.SH SEE ALSO
.B Angband(6)

.SH AUTHOR
Written by Group 18.
